---
openapi: 3.0.0
info:
  title: AHurynovich AWS Product Service API
  description: Documentation of AHurynovich AWS Product Service API (awesome guitars)
  contact:
    email: shagon1k@gmail.com
  version: 1.0.0-oas3
servers:
- url: https://j25gzwc0cl.execute-api.eu-west-1.amazonaws.com/prod
- url: http://j25gzwc0cl.execute-api.eu-west-1.amazonaws.com/prod
tags:
- name: productServiceProd
  description: Product Service production version
- name: productServiceDev
  description: Product Service development version
paths:
  /products:
    get:
      tags:
      - productServiceProd
      - productServiceDev
      description: |
        Get available products (guitars) list
      responses:
        "200":
          description: Available awesome guitars list response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        "500":
          description: Server error
    post:
      tags:
      - productServiceProd
      - productServiceDev
      description: |
        Add new awesome guitar to products catalog
      requestBody:
        description: Add new product request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddProduct'
      responses:
        "201":
          description: Guitar Added
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Product'
        "400":
          description: Passed product data is invalid
        "500":
          description: Server Error


  /products/{productId}:
    get:
      tags:
      - productServiceProd
      - productServiceDev
      description: |
        Get product (guitar) info by id
      parameters:
      - name: productId
        in: path
        description: Searched Guitar's ID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Found guitar info
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Product'
        "500":
          description: Server error
components:
  schemas:
    Product:
      required:
      - count
      - description
      - id
      - imageUrl
      - price
      - title
      type: object
      properties:
        id:
          type: string
          example: guitar-42
        title:
          type: string
          example: Hohner HC 03
        imageurl:
          type: string
          format: url
          example: http://dummy-url-to-image.com/img.jpg
        descripton:
          type: string
          example: Hohner HC 03 guitar
        count:
          type: number
          example: 2
        price:
          type: number
          example: 140
        priceGBP:
          type: number
          example: 98.5
    AddProduct:
      required:
      - title
      - description
      - imageUrl
      - price
      type: object
      properties:
        title:
          type: string
          example: Hohner HC 03
        descripton:
          type: string
          example: Hohner HC 03 guitar
        imageurl:
          type: string
          format: url
          example: http://dummy-url-to-image.com/img.jpg
        count:
          type: number
          example: 2
        price:
          type: number
          example: 140
