service:
  name: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${self:custom.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action: "sns:*"
      Resource:
        Ref: SNSTopic
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        - "${cf:import-service-${self:custom.stage}.SQSQueueArn}"
  environment:
    SNS_ARN:
      Ref: SNSTopic
    SQS_URL:
      - "${cf:import-service-${self:custom.stage}.SQSQueue}"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: "./config/webpack/webpack.config.js"   # Name of webpack configuration file
    packager: "npm"   # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
    keepOutputDirectory: true
  stage: ${opt:stage,dev}

resources:
  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: shagon1k@gmail.com
        Protocol: email
        TopicArn:
          Ref: SNSTopic

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          method: get
          path: products
          cors: true
  getProduct:
    handler: handler.getProduct
    events:
      - http:
          method: get
          path: products/{productId}
          cors: true
          request:
            parameters:
              paths:
                productId: true
  addProduct:
    handler: handler.addProduct
    events:
      - http:
          method: post
          path: products
          cors: true
          request:
            schema:
              application/json: ${file(swagger.yml):components.schemas.AddProduct} # ${file(config/models/add_product_request.json)}
  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            - "${cf:import-service-${self:custom.stage}.SQSQueueArn}"
