service:
  name: authorization-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${self:custom.stage}

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-function-outputs

custom:
  webpack:
    webpackConfig: "./config/webpack/webpack.config.js"   # Name of webpack configuration file
    packager: "npm"   # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
    keepOutputDirectory: true
  stage: ${opt:stage,dev}

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer